repos:
  - repo: https://github.com/gitguardian/gg-shield
    rev: v1.11.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
      - id: terragrunt_fmt
